### ISSUE TITLE
Fix Linux

### ISSUE THREAD

**Issue by ezpzbrah** [mcjp78/AltLoaderDownloads#1] opened 2016-05-16 14:26 UTC
When everyone was forced to update to version 0.3.1 of Alt Loader, Linux couldn't use 0.3.1 because only the oldest version of Alt Loader worked. When will a Linux version be released?!

**Comment by GramDev1** [comment] 2016-05-16 16:37
Working on this now.

Sent from my Apple Watch

On May 16, 2016, at 7:26 AM, ezpzbrah <notifications@github.com<mailto:notifications@github.com>> wrote:

When everyone was forced to update to version 0.3.1 of Alt Loader, Linux couldn't use it. When will a Linux version be released!

**Comment by ezpzbrah** [comment] 2016-05-16 23:20
Still not fixed :(

**Comment by GramDev1** [comment] 2016-05-16 23:22
Yes I know, will be patched in a few hours

**Comment by ezpzbrah** [comment] 2016-05-17 14:35
Yet, in 15 hours it's not patched :( I know I'm impatient.

**Comment by GramDev1** [comment] 2016-05-17 14:50
The error seems to be something whilst detecting the os. I just got s Linux box to test the software on

Sent from my iPhone

On May 17, 2016, at 7:35 AM, ezpzbrah <notifications@github.com<mailto:notifications@github.com>> wrote:

Yet, in 15 hours it's not patched :( I know I'm impatient.

##

**Comment by ezpzbrah** [comment] 2016-05-17 23:05
So will it be done today? (PCT timezone)

**Comment by GramDev1** [comment] 2016-05-17 23:10
Just finished it, I think. Test it?

**Comment by GramDev1** [comment] 2016-05-17 23:17
Patch confirmed working, closing this issue.

**Closed as completed by GramDev1** 2016-05-17 23:17 UTC
